name: Deploy Lambda

on:
  workflow_dispatch:   # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: AKIAUOHWXCZRUP4ZXHPF
        aws-secret-access-key: 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
        aws-region: eu-north-1

    - name: Package Lambda function
      run: |
        cd Lamda_Github_Test
        zip -r ../function.zip .
        cd ..

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name my-lambda \
          --zip-file fileb://function.zip
