name: Deploy Lambda

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: AKIAUOHWXCZRQL6TJEFT
        aws-secret-access-key: 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
        aws-region: eu-north-1

    - name: Deploy to Lambda
      run: |
        zip function.zip function.py
        aws lambda update-function-code \
          --function-name my-lambda \
          --zip-file fileb://function.zip
